const unitTable = `
CREATE TABLE IF NOT EXISTS units (
 unit_name VARCHAR(300) NOT NULL,
 unit_id INT AUTO_INCREMENT PRIMARY KEY,
 c_user VARCHAR(500) NOT NULL,
 c_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
 u_user VARCHAR(500),
 u_date TIMESTAMP DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP
)
`;

export { unitTable };
